### ISSUE TITLE
Time-Laps interval

### ISSUE THREAD

**Issue by hjoertel** [bitluni/ESP32CamTimeLapse#3]
Thanks for the project. It compiles and loads on the board.
But I'm not able to change the Time-Lapse interval using the web interface. no idea what happens but a picture is still taken every second like one can see at the flashing LED and the serial console.

**Comment by RBEGamer** [comment]
yeah i had the same problem; i pushed a pull request fixing this issue

**Comment by wzy-666** [comment]
I also had the same problem. Besides, the initial information of the setting can't be gotten.

**Comment by bitluni** [comment]
> yeah i had the same problem; i pushed a pull request fixing this issue

Which of your changes makes the interval work again?

**Comment by hjoertel** [comment]
> yeah i had the same problem; i pushed a pull request fixing this issue

I tried your changes, but still changing the time interval via web ui is not possible. The only change was that the camera is now taking a picture every 10s.

**Comment by feilimb** [comment]
Has this issue now been resolved? I noticed some pull requests were merged in recently.. (I was seeing the same issue when I tried to change the interval to every 30 seconds - photos were taken every second).

**Comment by bitluni** [comment]
To be honest I didn't have time to test it.. it was a pure trust merge.
please let me know if it works for you :-)

**Comment by feilimb** [comment]
@bitluni I just uploaded the latest code to my esp32cam - and all is good :) the pull requests did indeed resolve this issue with the interval now working in the web interface.  It seems you can even change the interval while a time lapse is underway.  I started at a 30s interval, and then reduced to 10s, and finally went to 5s interval - I could see from serial output that frames were adjusting to each new interval.

Thanks for the work, I did a hack on the original code also a month back where I added a control to turn on/off a strip of 5 APA102 LEDs (RGB), and a slider to control their brightness.  Then I placed the cam inside a bird nestbox in back garden - but after no birds decided to move into the vacant box after 6 weeks I ripped the esp32cam out again :)

**Comment by hjoertel** [comment]
Am Donnerstag, 6. Februar 2020, 20:20:55 CET schrieb bitluni:
> To be honest I didn't have time to test it.. it was a pure trust merge.
> please let me know if it works for you :-)

It works now for me too. Thanks for fixing the code.

Does make sense to have 'halt' button to savely remove power and the SD Card?

Regards
 Heinz
