### ISSUE TITLE
Missing esp_camera-h

### ISSUE THREAD

**Issue by marsrakete** [bitluni/ESP32CamTimeLapse#7]
Pulled master of today. Compiling yields into an error:

camera.h:2:24: error: esp_camera.h: No such file or directory
 #include "esp_camera.h"

What am I missing here? A library?

**Comment by hjoertel** [comment]
check if you have selected the correct board "Boards: ESP Wrover Module" and camera module: #define CAMERA_MODEL_AI_THINKER
At least for me the code compiles. after git clone I only edited the WLAN settings

**Comment by marsrakete** [comment]
This board is not listed in my board manager. I have installed boards list version 2.6.3 of the ESP8266 Community. Arduino IDE 1.8.10 here.

In camera.cpp:
// WARNING!!! Make sure that you have either selected ESP32 Wrover Module, or another board which has PSRAM enabled

CAMERA_MODEL_AI_THINKER is activated.

My board should have PSRAM. Although, I am unsure how to prove and which board to select.

I bought this board:
KeeYees WiFi + Bluetooth Modul Kit 4M PSRAM ESP32-CAM Dual-Core 32 Bit CPU” (www.amazon.de/gp/product/B07S83X9NM/)

The boards works good so far, but not this code regardless which board I choose in the list

**Comment by bitluni** [comment]
You need the esp32 board plugin (esp8266 is different)
https://github.com/espressif/arduino-esp32

millenseer <notifications@github.com> schrieb am Mo., 10. Feb. 2020, 14:06:

**Comment by marsrakete** [comment]
Oh, darn. I switched to a newly setup arduino IDE version and apparently forgot to setup the right boards. Thanks for the hint! Does compile and even better - it works now!

But - how do I access the time lapse images written to /lapse000 ? Removing the card? Will try to hack an ftp upload :-)
